name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */10 * * *' # Berjalan setiap 10 jam
  workflow_dispatch: # Membolehkan anda jalan secara manual

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Streamlit via HTTP Ping
        run: |
          curl -sI https://kml2shp.streamlit.app/ | head -n 1
